"""Context window management: token counting and sliding-window compression.

Tracks token usage across the conversation and triggers summarization
when approaching the context window limit.
"""

from __future__ import annotations

import logging

import tiktoken

from codey.agent.message_types import Message
from codey.telemetry.event_bus import EventBus, Events

logger = logging.getLogger(__name__)

# Default context window sizes by known model patterns
MODEL_CONTEXT_SIZES: dict[str, int] = {
    "deepseek": 128_000,
    "llama-3.3": 131_072,
    "gemini-2.5": 1_000_000,
    "gemini-2.0": 1_000_000,
    "llama3.3": 131_072,
    "qwen": 32_000,
}

DEFAULT_CONTEXT_SIZE = 32_000


class ContextManager:
    """Manages conversation token budget and context compression.

    Uses tiktoken (cl100k_base) for approximate token counting across all
    providers.  Accuracy is ±10% for non-OpenAI models — the context meter
    will show '≈' to indicate approximate counts.

    When token usage exceeds the configurable threshold, the oldest messages
    are compressed into a summary.
    """

    def __init__(
        self,
        event_bus: EventBus,
        max_context_tokens: int = DEFAULT_CONTEXT_SIZE,
        compression_threshold: float = 0.80,
    ) -> None:
        self.event_bus = event_bus
        self.max_context_tokens = max_context_tokens
        self.compression_threshold = compression_threshold

        # Use cl100k_base as a reasonable approximation for all models
        try:
            self._encoder = tiktoken.get_encoding("cl100k_base")
        except Exception:
            logger.warning("tiktoken unavailable, falling back to char-based estimation")
            self._encoder = None

        self._is_approximate = True  # Always approximate for non-OpenAI

    def count_tokens(self, text: str) -> int:
        """Count tokens in a string."""
        if self._encoder:
            return len(self._encoder.encode(text, disallowed_special=()))
        # Fallback: ~4 chars per token
        return max(1, len(text) // 4)

    def count_message_tokens(self, message: Message) -> int:
        """Count tokens in a single message (content + tool calls + overhead)."""
        tokens = 4  # Per-message overhead (role, separators)

        if message.content:
            tokens += self.count_tokens(message.content)

        if message.tool_calls:
            for tc in message.tool_calls:
                tokens += self.count_tokens(tc.name)
                tokens += self.count_tokens(str(tc.arguments))
                tokens += 4  # Tool call structure overhead

        if message.tool_call_id:
            tokens += self.count_tokens(message.tool_call_id)

        return tokens

    def count_conversation_tokens(self, messages: list[Message]) -> int:
        """Count total tokens across all messages."""
        total = 3  # Conversation overhead (priming)
        for msg in messages:
            total += self.count_message_tokens(msg)
        return total

    def get_usage(self, messages: list[Message]) -> dict:
        """Get current context usage info and emit update event.

        Returns:
            dict with keys: used, total, percent, approximate
        """
        used = self.count_conversation_tokens(messages)
        pct = (used / self.max_context_tokens) * 100 if self.max_context_tokens > 0 else 0

        usage = {
            "used": used,
            "total": self.max_context_tokens,
            "percent": min(pct, 100.0),
            "approximate": self._is_approximate,
        }

        self.event_bus.emit(Events.CONTEXT_UPDATE, **usage)
        return usage

    def needs_compression(self, messages: list[Message]) -> bool:
        """Check if the conversation needs context compression."""
        used = self.count_conversation_tokens(messages)
        return used >= (self.max_context_tokens * self.compression_threshold)

    def compress_history(
        self,
        messages: list[Message],
        preserve_recent: int = 6,
    ) -> list[Message]:
        """Compress older messages into a summary, preserving recent context.

        Strategy:
          1. Keep the system message (index 0).
          2. Keep the last `preserve_recent` messages.
          3. Summarize everything in between into a single system message.

        Note: In Phase 2+, the summary will be generated by the active model.
        For now, we do a simple truncation with metadata preservation.
        """
        if len(messages) <= preserve_recent + 2:
            return messages  # Nothing to compress

        system_msg = messages[0] if messages[0].role == "system" else None
        start_idx = 1 if system_msg else 0
        cut_point = len(messages) - preserve_recent

        # Build summary of compressed messages
        compressed_section = messages[start_idx:cut_point]
        summary_parts = []
        tool_calls_seen = set()

        for msg in compressed_section:
            if msg.role == "user":
                summary_parts.append(f"User asked: {self._truncate(msg.content, 100)}")
            elif msg.role == "assistant" and msg.content:
                summary_parts.append(f"Assistant: {self._truncate(msg.content, 150)}")
            elif msg.role == "assistant" and msg.tool_calls:
                for tc in msg.tool_calls:
                    tool_calls_seen.add(tc.name)
            elif msg.role == "tool":
                summary_parts.append(f"Tool result received")

        summary_text = (
            "[Context compressed — earlier conversation summary]\n"
            f"Tools used: {', '.join(tool_calls_seen) if tool_calls_seen else 'none'}\n"
            + "\n".join(summary_parts[-10:])  # Keep last 10 summary items
        )

        summary_msg = Message(role="system", content=summary_text)

        # Reconstruct: system + summary + recent
        result = []
        if system_msg:
            result.append(system_msg)
        result.append(summary_msg)
        result.extend(messages[cut_point:])

        logger.info(
            "Compressed %d messages to %d (saved ~%d tokens)",
            len(messages),
            len(result),
            self.count_conversation_tokens(compressed_section),
        )
        return result

    def set_context_size_for_model(self, model_id: str) -> None:
        """Auto-detect context window size based on model identifier."""
        model_lower = model_id.lower()
        for pattern, size in MODEL_CONTEXT_SIZES.items():
            if pattern in model_lower:
                self.max_context_tokens = size
                logger.info(
                    "Set context window to %d tokens for model %s", size, model_id
                )
                return
        logger.info(
            "Using default context window %d for model %s",
            DEFAULT_CONTEXT_SIZE,
            model_id,
        )

    @staticmethod
    def _truncate(text: str | None, max_len: int) -> str:
        if not text:
            return "(empty)"
        if len(text) <= max_len:
            return text
        return text[:max_len] + "..."
